#include "catch2/catch.hpp"

static int getInt(int x)
{
    int xsquared = x * x;
    return xsquared;
}

TEST_CASE("CLion demo")
{
    // Trivial example code for https://youtrack.jetbrains.com/issue/CPP-1420
    int x = 2;
    int xsquared = getInt(x);
    CHECK(xsquared == 4);
}

// Steps done:
// * Select line 7
// * Extract method
// * Select "Above"
// * Click "OK"

// Fixed output, as previously generated by CLion 2020.3
// Build #CL-203.5981.166, built on December 1, 2020
